plugins {
    id 'java-library'
    id 'maven-publish'
    id 'com.gradleup.shadow' version "${shadow_version}"
    id 'net.linguica.maven-settings' version "${maven_settings_version}"
    id "de.undercouch.download" version "${gradle_download_task_version}"
}

group = 'de.maxhenkel.rnnoise4j'
archivesBaseName = 'rnnoise4j'
version = library_version

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.named('sourcesJar', Jar) {
    exclude 'natives/**'
    exclude '**/*.bin'
}

def generatedResourcesDir = layout.buildDirectory.dir("generated-resources")

sourceSets {
    main {
        resources {
            srcDir generatedResourcesDir
        }
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.maxhenkel.de/repository/public' }
}

dependencies {
    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'

    implementation "de.maxhenkel.native-utils:native-utils:${nativeutils_version}"

    testImplementation platform("org.junit:junit-bom:${junit_version}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testImplementation 'org.junit.platform:junit-platform-launcher'
}

shadowJar {
    archiveClassifier = ''
    relocate("de.maxhenkel.nativeutils", "de.maxhenkel.rnnoise4j")
}
tasks.assemble.dependsOn tasks.shadowJar

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            pom {
                name = 'RNNoise4J'
                description = 'RNNoise Wrapper for Java'
                url = 'https://maxhenkel.de'
            }
        }
    }
    repositories {
        maven {
            name = 'henkelmax.public'
            url = uri('https://maven.maxhenkel.de/repository/public')
        }
    }
}

tasks.register("fetchWeights", Download) {
    src "https://github.com/henkelmax/rnnoise-weights/releases/download/v0.2/weights_blob_small.bin"
    dest generatedResourcesDir.get().file("rnnoise/weights_blob.bin")
    onlyIfModified true
}

tasks.named("processResources") {
    dependsOn("fetchWeights")
}

def platforms = [
        [
                name  : 'linux-arm64',
                file  : 'zig-aarch64-linux-gnu.cmake',
                res   : 'linux-aarch64',
                libExt: 'so'
        ],
]

platforms.each { target ->
    def safeName = target.name.capitalize().replace('-', '')
    def configureTask = "configureNatives${safeName}"
    def buildTask = "buildNatives${safeName}"
    def copyTask = "copyNatives${safeName}"

    def cmakeListsPath = "../../CMakeLists.txt"
    def cmakePlatformPath = "../../cmake/${target.file}"
    def buildDir = layout.projectDirectory.dir("native/build/${target.res}")
    def resourceDir = generatedResourcesDir.get().dir("natives/${target.res}")
    def cSourcesDir = layout.projectDirectory.dir('native/src')
    def outputName = "librnnoise4j.${target.libExt}"

    tasks.register(configureTask, Exec) {
        group = 'natives'
        description = "CMake configure for ${target.name}"
        workingDir = buildDir

        inputs.file(buildDir.file(cmakeListsPath))
        inputs.file(buildDir.file(cmakePlatformPath))
        inputs.dir(cSourcesDir)
        outputs.dir(buildDir)

        doFirst {
            def dir = buildDir.asFile
            if (dir.exists()) {
                logger.lifecycle("Cleaning ${dir}")
                project.delete(fileTree(dir: dir))
            }
            dir.mkdirs()
        }

        commandLine 'cmake',
                "-DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/28.2.13676358/build/cmake/android.toolchain.cmake",
                '-DCMAKE_BUILD_TYPE=Release',
                '-DANDROID_PLATFORM=24',
                '-DANDROID_ABI=arm64-v8a',
                '-DCMAKE_SYSTEM_NAME=Android',
                '-G', 'Ninja',
                '../..'
    }

    tasks.register(buildTask, Exec) {
        group = 'natives'
        description = "Build natives for ${target.name}"
        workingDir = buildDir
        dependsOn configureTask

        inputs.dir(buildDir)
        outputs.dir(buildDir)

        commandLine 'cmake', '--build', '.', '--config', 'Release', '--parallel', '4'
    }

    tasks.register(copyTask, Copy) {
        group = 'natives'
        description = "Copy ${target.name} natives into resources"
        dependsOn buildTask

        from buildDir.file(outputName)
        into resourceDir
    }
}

tasks.register('buildAndCopyAllNatives') {
    group = 'natives'
    description = 'Build & copy all native libraries for every platform/arch'
    dependsOn platforms.collect { "copyNatives${it.name.capitalize().replace('-', '')}" }
}

tasks.named('processResources') {
    dependsOn 'buildAndCopyAllNatives'
}

tasks.named("clean", Delete).configure {
    delete("native/build")
}
